### ISSUE TITLE
Missing "version" property in Statement model

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/model#48]
See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#2410-version.

Our Statement model is currently missing a version property.

**Comment by xabbuh** [comment]
The `SubStatement` class does not need to be changed as [the `version` attribute is not allowed](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#substatements) there:

> A SubStatement MUST NOT have the "id", "stored", "version" or "authority" properties.
