### ISSUE TITLE
$actor property of State model should be an Agent

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/model#49]
instead of an Actor (= Agent or Group).

**Comment by Lctrs** [comment]
Little explanation : 

See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#242-actor

> The Actor defines who performed the action. The Actor of a Statement can be an Agent or a Group.

And next, the following parts of the spec : 
- https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#23-state-resource
- https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#26-agent-profile-resource
- https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#27-activity-profile-resource

Where they said Agent and not Actor in all this parts.

**Comment by Lctrs** [comment]
@xabbuh I can make a PR for this.

Just a question, do you want it to be BC or not ?

**Comment by xabbuh** [comment]
The PR should just replace the old type hint with the new one and change variable names accordingly. I did not make a final decision yet whether I will treat this as a BC break or not. For now, let's treat it as a bug fix.
