### ISSUE TITLE
Should we move the filters classes to php-xapi/repository-api package ?

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/model#50]
Thoses classes only exist to serve as criterias for the repositories interfaces. I think we should move them into this package then. Or maybe I'm missing something ?

**Comment by xabbuh** [comment]
They are also used by the client to get a filtered list of statements: https://github.com/php-xapi/client/blob/master/src/Api/StatementsApiClientInterface.php#L108

**Comment by xabbuh** [comment]
And I think we could probably also make use of the `StateDocumentsFilter` there after it is merged.
